### ISSUE TITLE
구글 로그인하는데 CORS 에러가 납니다

### ISSUE THREAD

**Issue by choi8686** [depromeet/InsightOut-client#196]
![스크린샷 2023-08-09 오후 3 46 30](https://github.com/depromeet/InsightOut-client/assets/37816932/a21339dc-da50-482e-bc62-8fca1d4b08ed)

둘러보다가 배포된 사이트에 가서 해봤는데 안되서 이슈 남겼습니다.

**Comment by newminkyung** [comment]
안녕하세요, @choi8686 님! 

우선 서비스에 관심을 가져주셔서 감사합니다!

<br />

**현재 수정이 완료되어 로그인이 정상적으로 작동합니다**


---

아직 개발 진행 중인 서비스라 주로 개발 환경만 고려하다보니 중간에 프로덕션 코드가 변경된 것을 인지하지 못했었네요. 
기존에 사용하던 API 주소로 다시 변경하여 문제를 해결하였습니다. 

이슈를 남겨주신 덕분에 에러를 빠르게 해결할 수 있었습니다 👍

---

더 궁금한 점이나 서비스 이용에 불편함이 있다면 언제든지 이슈 남겨주세요! 
좋은 하루 되세요 감사합니다 :)
